# Pack Information
pack_name = More Compatibility Variants (Oh The Biomes We've Gone)
pack_name_short = More Compatibility Variants (OTBWG)
pack_description = Adding compatibility for Oh The Biomes We've Gone's wood types to More Variants Mods. This is NOT an expansion, it simply fixes a crafting issue between these mods and Oh The Biomes We've Gone.
pack_version = 1.0.4
dependencies = oh-the-biomes-weve-gone(required){modrinth:BzOTnuqM}{curseforge:1070751}

# Minecraft Version
minecraft_version_supported = [1.21,1.21.1]
minecraft_version_name = 1.21(.1)

archives_base_name = More-Compatibility-Variants-OTBWG

# Publishing Data
minecraft_version_filter = releases
modrinth_id = jwSzLWcy
curseforge_id = 1184221
license = CC-BY-NC-SA-4.0